
name: "custom-gnuradio-aarch64"

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: cachix/install-nix-action@v17
      - uses: cachix/cachix-action@v10
        with:
          name: dump-dvb
          authToken: '${{ secrets.CACHIX_AUTH_TOKEN }}'
      - run: nix build -vL .\#packages.aarch64.custom-gnuradio
      - run: nix build -vL .\#packages.aarch64.gnuradio-decode
